In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl

In [20]:
df = pd.read_csv('files/movies.csv',
                 header = None,
                 sep = '|',
                 na_values = ['', '?'])
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Color,James Cameron,723.0,178.0,760505847.0,Avatar,3054.0,USA,PG-13,"237,000,000.0",2009.0,7.9,Action
1,Color,Gore Verbinski,302.0,169.0,309404152.0,Pirates of the Caribbean: At World's End,1238.0,USA,PG-13,"300,000,000.0",2007.0,7.1,Action
2,Color,Sam Mendes,602.0,148.0,200074175.0,Spectre,994.0,UK,PG-13,"245,000,000.0",2015.0,6.8,Action
3,Color,Christopher Nolan,813.0,164.0,448130642.0,The Dark Knight Rises,2701.0,USA,PG-13,"250,000,000.0",2012.0,8.5,Action
4,NaN,Doug Walker,NaN,NaN,NaN,Star Wars: Episode VII - The Force Awakens ...,NaN,NaN,NaN,NaN,NaN,7.1,Documentary

In [21]:
df.shape

(100, 13)

In [22]:
df.isna().sum()

0     1
1     0
2     1
3     1
4     3
5     0
6     1
7     1
8     2
9     4
10    1
11    0
12    0
dtype: int64

In [28]:
df[df.isna().any(axis=1)]

,0,1,2,3,4,5,6,7,8,9,10,11,12
4,NaN,Doug Walker,NaN,NaN,NaN,Star Wars: Episode VII - The Force Awakens ...,NaN,NaN,NaN,NaN,NaN,7.1,Documentary
55,Color,Peter Sohn,298.0,93.0,123070338.0,The Good Dinosaur,345.0,USA,PG,NaN,2015.0,6.8,Adventure
84,Color,Roland Joffé,10.0,109.0,NaN,The Lovers,15.0,Belgium,R,NaN,2015.0,4.5,Action
98,Color,Hideaki Anno,1.0,120.0,NaN,Godzilla Resurgence,13.0,Japan,NaN,NaN,2016.0,8.2,Action

In [32]:
df = df.dropna()

In [40]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,Color,James Cameron,723.0,178.0,760505847.0,Avatar,3054.0,USA,PG-13,"237,000,000.0",2009.0,7.9,Action
1,Color,Gore Verbinski,302.0,169.0,309404152.0,Pirates of the Caribbean: At World's End,1238.0,USA,PG-13,"300,000,000.0",2007.0,7.1,Action
2,Color,Sam Mendes,602.0,148.0,200074175.0,Spectre,994.0,UK,PG-13,"245,000,000.0",2015.0,6.8,Action
3,Color,Christopher Nolan,813.0,164.0,448130642.0,The Dark Knight Rises,2701.0,USA,PG-13,"250,000,000.0",2012.0,8.5,Action
5,Color,Andrew Stanton,462.0,132.0,73058679.0,John Carter,738.0,USA,PG-13,"263,700,000.0",2012.0,6.6,Action
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Color,Jonathan Mostow,280.0,109.0,150350192.0,Terminator 3: Rise of the Machines,1676.0,USA,R,"200,000,000.0",2003.0,6.4,Action
95,Color,James Gunn,653.0,121.0,333130696.0,Guardians of the Galaxy,1097.0,USA,PG-13,"170,000,000.0",2014.0,8.1,Action
96,Color,Christopher Nolan,712.0,169.0,187991439.0,Interstellar,2725.0,USA,PG-13,"165,000,000.0",2014.0,8.6,Adventure
97,Color,Christopher Nolan,642.0,148.0,292568851.0,Inception,2803.0,USA,PG-13,"160,000,000.0",2010.0,8.8,Action
99,Color,Peter Jackson,645.0,182.0,303001229.0,The Hobbit: An Unexpected Journey,1367.0,USA,PG-13,"180,000,000.0",2012.0,7.9,Adventure

In [38]:
column_names = ['color', 'director_name', 'num_critic_for_reviews', 'duration',
                'gross', 'movie_title', 'num_user_for_reviews',	'country',
                'cotent_rating', 'budget', 'title_year', 'imdb_score', 'genre']

In [42]:
df.columns = column_names
df

,color,director_name,num_critic_for_reviews,duration,gross,movie_title,num_user_for_reviews,country,cotent_rating,budget,title_year,imdb_score,genre
0,Color,James Cameron,723.0,178.0,760505847.0,Avatar,3054.0,USA,PG-13,"237,000,000.0",2009.0,7.9,Action
1,Color,Gore Verbinski,302.0,169.0,309404152.0,Pirates of the Caribbean: At World's End,1238.0,USA,PG-13,"300,000,000.0",2007.0,7.1,Action
2,Color,Sam Mendes,602.0,148.0,200074175.0,Spectre,994.0,UK,PG-13,"245,000,000.0",2015.0,6.8,Action
3,Color,Christopher Nolan,813.0,164.0,448130642.0,The Dark Knight Rises,2701.0,USA,PG-13,"250,000,000.0",2012.0,8.5,Action
5,Color,Andrew Stanton,462.0,132.0,73058679.0,John Carter,738.0,USA,PG-13,"263,700,000.0",2012.0,6.6,Action
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Color,Jonathan Mostow,280.0,109.0,150350192.0,Terminator 3: Rise of the Machines,1676.0,USA,R,"200,000,000.0",2003.0,6.4,Action
95,Color,James Gunn,653.0,121.0,333130696.0,Guardians of the Galaxy,1097.0,USA,PG-13,"170,000,000.0",2014.0,8.1,Action
96,Color,Christopher Nolan,712.0,169.0,187991439.0,Interstellar,2725.0,USA,PG-13,"165,000,000.0",2014.0,8.6,Adventure
97,Color,Christopher Nolan,642.0,148.0,292568851.0,Inception,2803.0,USA,PG-13,"160,000,000.0",2010.0,8.8,Action
99,Color,Peter Jackson,645.0,182.0,303001229.0,The Hobbit: An Unexpected Journey,1367.0,USA,PG-13,"180,000,000.0",2012.0,7.9,Adventure

In [49]:
df.loc[(df['imdb_score'] > 8)]

,color,director_name,num_critic_for_reviews,duration,gross,movie_title,num_user_for_reviews,country,cotent_rating,budget,title_year,imdb_score,genre
3,Color,Christopher Nolan,813.0,164.0,448130642.0,The Dark Knight Rises,2701.0,USA,PG-13,"250,000,000.0",2012.0,8.5,Action
17,Color,Joss Whedon,703.0,173.0,623279547.0,The Avengers,1722.0,USA,PG-13,"220,000,000.0",2012.0,8.1,Action
27,Color,Anthony Russo,516.0,147.0,407197282.0,Captain America: Civil War,1022.0,USA,PG-13,"250,000,000.0",2016.0,8.2,Action
43,Color,Lee Unkrich,453.0,103.0,414984497.0,Toy Story 3,733.0,USA,G,"200,000,000.0",2010.0,8.3,Adventure
58,Color,Andrew Stanton,421.0,98.0,223806889.0,WALL·E,1043.0,USA,G,"180,000,000.0",2008.0,8.4,Adventure
66,Color,Christopher Nolan,645.0,152.0,533316061.0,The Dark Knight,4667.0,USA,PG-13,"185,000,000.0",2008.0,9.0,Action
67,Color,Pete Docter,408.0,96.0,292979556.0,Up,704.0,USA,PG,"175,000,000.0",2009.0,8.3,Adventure
78,Color,Pete Docter,536.0,95.0,356454367.0,Inside Out,773.0,USA,PG,"175,000,000.0",2015.0,8.3,Adventure
93,Color,Dean DeBlois,288.0,98.0,217387997.0,How to Train Your Dragon,492.0,USA,PG,"165,000,000.0",2010.0,8.2,Adventure
95,Color,James Gunn,653.0,121.0,333130696.0,Guardians of the Galaxy,1097.0,USA,PG-13,"170,000,000.0",2014.0,8.1,Action
96,Color,Christopher Nolan,712.0,169.0,187991439.0,Interstellar,2725.0,USA,PG-13,"165,000,000.0",2014.0,8.6,Adventure
97,Color,Christopher Nolan,642.0,148.0,292568851.0,Inception,2803.0,USA,PG-13,"160,000,000.0",2010.0,8.8,Action

In [54]:
df.duplicated().any().sum()

0